- name: install docker engine
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: install docker engine
      when: ansible_os_family == 'Debian'
      script: ./scripts/install-docker-ubuntu.sh