# Sample config for Grafana Agent
# For a full configuration reference, see: https://grafana.com/docs/agent/latest/configuration/.
server:
  log_level: warn

metrics:
  global:
    scrape_interval: 1m
    remote_write:
      - url: 'url'
        basic_auth:
          username: 'username'
          password: 'token'
  wal_directory: '/var/lib/grafana-agent'
  configs:
     - name: agent
       host_filter: false
       scrape_configs:
         - job_name: agent
           static_configs:
             - targets: ['::1:9090']

integrations:
  agent:
    enabled: true
  node_exporter:
    enabled: true
    include_exporter_metrics: true
    disable_collectors:
      - "mdadm"
