- name: install docker engine
  hosts: docker
  become: true
  become_user: root
  tasks:
    - name: install dependencies
      when: ansible_distribution_release == 'jammy'
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
    - name: add GPG key
      when: ansible_distribution_release == 'jammy'
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: add docker repository to apt
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present
    - name: install docker
      when: ansible_distribution_release == 'jammy'
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
    - name: checking docker is installed
      when: ansible_distribution_release == 'jammy'
      service:
        name: docker
        state: started
        enabled: yes