- name: DEVGRU Router 66
  hosts: hydra-2
  become: true
  become_user: root
  tasks:
    - name: traefik
      ansible.builtin.docker_container:
        name: traefik
        image: traefik:2.10
        command:
          - "--log.level=DEBUG"
          - "--api.insecure=true"
          - "--providers.docker=true"
          - "--providers.docker.exposedbydefault=false"
          - "--entrypoints.web.address=:80"
        state: started
        ports:
          - "[::]:80:80"
          - "[::]:8080:8080"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
    
    - name: whoami
      ansible.builtin.docker_container:
        name: whoami
        image: "traefik/whoami"
        labels:
          traefik.enable: "true"
          traefik.http.routers.whoami.rule: "Host(`hydra-2.techalchemist.pl`)"
          traefik.http.routers.whoami.entrypoints: "web"
    
    - name: postgres
      ansible.builtin.docker_container:
        name: postgres
        image: postgres
        env:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "changeme"
          PGDATA: /data/postgres
        labels:
          traefik.enable: "true"
          traefik.tcp.routers.postgres.rule: "Host(`pgsql.techalchemist.pl`)"
          traefik.tcp.routers.postgres.entrypoints: "tcp"
          traefik.tcp.services.postgres.loadbalancer.server.port: "5432"
