- name: DEVGRU Router 66
  hosts: hydra-2
  become: true
  become_user: root
  tasks:
    - name: traefik
      ansible.builtin.docker_container:
        name: traefik
        image: traefik:2.10
        commands:
          - "--log.level=DEBUG"
          - "--api.insecure=true"
          - "--providers.docker=true"
          - "--providers.docker.exposedbydefault=false"
          - "--entrypoints.web.address=:80"
        state: present
        exposed_ports:
          - "80:80"
          - "8080:8080"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock:ro"